version: "3.7"

services:
  myapp:
    build:
      context: .
      dockerfile: dockerfile
    container_name: travel1
    command: sh -c "grep 'PRETTY_NAME' /etc/os-release && google-chrome --version && npm -v && npm i --silent && npm run tests-testcafe-screenshots"
    working_dir: /myapp
    volumes:
      - ../:/myapp
