# syntax=docker/dockerfile:1
# node:latest tooks 1.7Gb, node:slim tooks 1Gb
#FROM node:latest
FROM node:slim
RUN echo "started"
RUN apt-get update
RUN apt-get install -y wget
RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt-get install -y ./google-chrome-stable_current_amd64.deb
RUN rm google-chrome-stable_current_amd64.deb
RUN echo "finished"
