name: Testcafe tests

# More details:
# https://github.com/IgnatovDan/Sandbox/blob/main/.github/workflows/TestGithubActionsForBranches.yml

on: 
  # Force workflow after each change in any branch
  push:
  workflow_dispatch:

jobs:
  screenshot_tests:
    name: Testcafe screenshot tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Run testcafe screenshot tests
        run: npm run tests-testcafe-screenshots

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: testcafe-results
          path: tests-testcafe/_temp-screenshots-comparer/artifacts/compared-screenshots
          if-no-files-found: ignore
          retention-days: 1
